name: Build Docker image
description: Build and cache the PHP Docker image

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4

    - name: Build Docker image
      uses: docker/build-push-action@v7
      with:
        context: .
        file: .infra/docker/php.Dockerfile
        load: true
        tags: padi-php:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
